### ISSUE TITLE
Clean library

### ISSUE THREAD

**Issue by dave-plutoflume** [gatewayapps/node-tnef#1]
This library could be really useful, but appears to be heavily polluted with `console.log()` statements and a requirement to save attachment data to separate files.

It would be nice to have a simple interface consistent with other NodeJS libraries.
Example
```
const tnef = require('node-tnef');

tnef.parse('/some/path/to/a/tnef/file.dat', function(err, content) {
});
```

the `parse()` function would call the callback with a `content` object containing the parsed data, or an error if it cannot be parsed.

Another (perhaps better) implementation would accept a buffer or stream, leaving the data retrieval up to the caller:
```
const tnef = require('node-tnef');

const tnef_buffer = Buffer.from([/*some.tnef.data,bytes*/])

tnef.parse(tnef_buffer, function(err, content) {
});
```

**Comment by johnmurphy01** [comment]
Thanks for the feedback! Primarily this library was built as a console application not to be run within another Node project. Now that there is an expressed desire for this, I am more willing to go ahead and implement. 

As for the `console.log()` statements, they exist in order to provide meaningful feedback to the user running the console application. 

Also, as this is an open source project feel free to submit a PR if you wish to contribute.

**Comment by johnmurphy01** [comment]
@dave-plutoflume I have a PR here https://github.com/gatewayapps/node-tnef/pull/2 that I _think_ will achieve what you have requested. I'm going to look over it some more but also feel free to take a gander if you'd like and then I'll merge it.

**Comment by johnmurphy01** [comment]
Version `1.2.0`
